FYPWeb/Controllers/Api/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Http;
using FYPWeb.Enum;
using FYPWeb.Hub;
using FYPWeb.Repository.Repository;
using FYPWeb.Services.Util;
using Model.Entity;

namespace FYPWeb.Controllers.Api
{
    public class EmployeeController : ApiController
    {
        private readonly EmployeeRepository _employeeRepository;
        private readonly NotificationRepository _notificationRepository;
        public EmployeeController(EmployeeRepository employeeRepository, NotificationRepository notificationRepository)
        {
            _employeeRepository = employeeRepository;
            _notificationRepository = notificationRepository;
        }

        [HttpPost]
        public IHttpActionResult GetEmployeeById([FromBody] GetEmployeeParameter parameter)
        {
            try
            {
                if (parameter != null && parameter.EmployeeId > 0)
                {
                    var employee = _employeeRepository.GetById(parameter.EmployeeId);
                    return Ok(new
                    {
                        result = employee.ForJson(),
                        message = "Success"
                    });
                }

            }
            catch (Exception e)
            {
                Debug.WriteLine(e);
            }
            return InternalServerError();
        }

        [HttpPost]
        public IHttpActionResult GetAllEmployees([FromBody] GetEmployeeParameter parameter)
        {
            try
            {
                if (parameter != null && parameter.UserId > 0)
                {
                    var page = parameter?.Page > 0 ? parameter.Page : 1;
                    if (string.IsNullOrEmpty(parameter?.Search))
                    {
                        var list = _employeeRepository.GetEmployeesByUserId(parameter.UserId,page).Select(p => p.ForJson());
                        var pageCount = _employeeRepository.GetCountEmployeesByUserId(parameter.UserId);
                        return Ok(new
                        {
                            result = list,
                            pageCount = pageCount,
                            message = "Success",
                        });
                    }
                    else
                    {
                        var list =
                            _employeeRepository.GetEmployeesSearchByUserId(parameter.UserId,parameter.Search, page).Select(p => p.ForJson());
                        var pageCount = _employeeRepository.GetCountEmployeesSearchByUserId(parameter.UserId,parameter.Search);
                        return Ok(new
                        {
                            result = list,
                            pageCount = pageCount,
                            message = "Success",
                        });
                    }
                }
            }
            catch (Exception e)
            {
                Debug.WriteLine(e);
            }
            return InternalServerError();
        }
        [HttpPost]
        public IHttpActionResult SaveEmployee([FromBody] SaveEmployeeParameter parameter)
        {
            try
            {
                if (parameter != null && parameter.UserId > 0)
                {
                    var e = new Employee()
                    {
                        Address = parameter.Address,
                        ContactNumber = parameter.PhoneNumber,
                        DutyHours = parameter.DutyHours,
                        ImageLink = UtilService.DefaultImagePath,
                        Name = parameter.Name,
                        Salary = parameter.Salary,
                        UserId = parameter.UserId,
                    };
                    _employeeRepository.Add(e);
                    
                    var notification = new Notification()
                    {
                        Url = "/Pharmacy/Employee/",
                        Body = "You have created an Employee. Assign it a Pharmacy",
                        CreatedAt = DateTime.Now,
                        IsPharmacy = false,
                        IsPost = false,
                        IsSeen = false,
                        ReceiverUserId = parameter.UserId,
                        NotificationType = (int)NotificationType.Info,
                    };
                    _notificationRepository.Add(notification);
                    NotificationHub.StaticSendNotification(notification, notification.ReceiverUserId, notification.NotificationType);
                    return Ok(new
                    {
                        result = e.Id,
                        message = "Success"
                    });
                }
            }
            catch (Exception e)
            {
                Debug.WriteLine(e);
            }
            return InternalServerError();
        }
        [HttpPost]
        public IHttpActionResult UpdateEmployee([FromBody] SaveEmployeeParameter parameter)
        {
            try
            {
                if (parameter != null && parameter.UserId > 0 && parameter.Id > 0)
                {

                    var e = _employeeRepository.GetByIdAndUser(parameter.Id, parameter.UserId);
                    e.Address = parameter.Address;
                    e.ContactNumber = parameter.PhoneNumber;
                    e.DutyHours = parameter.DutyHours;
                    e.Name = parameter.Name;
                    e.Salary = parameter.Salary;
                    _employeeRepository.Update(e);
                    return Ok(new
                    {
                        result = "",
                        message = "Success"
                    });
                }
            }
            catch (Exception e)
            {
                Debug.WriteLine(e);
            }
            return InternalServerError();
        }
        [HttpPost]
        public IHttpActionResult AssignEmployee([FromBody] SaveEmployeeParameter parameter)
        {
            try
            {
                if (parameter != null && parameter.UserId > 0 && parameter.Id > 0 && parameter.PharmacyId > 0)
                {

                    var e = _employeeRepository.GetByIdAndUser(parameter.Id, parameter.UserId);
                    e.PharmacyId = parameter.PharmacyId;
                    _employeeRepository.Update(e);
                    return Ok(new
                    {
                        result = e.Id,
                        message = "Success"
                    });
                }
            }
            catch (Exception e)
            {
                Debug.WriteLine(e);
            }
            return InternalServerError();
        }
        [HttpPost]
        public IHttpActionResult DeleteEmployee([FromBody] SaveEmployeeParameter parameter)
        {
            try
            {
                if (parameter != null && parameter.Id > 0)
                {

                    var e = _employeeRepository.GetById(parameter.Id);
                    if (e != null)
                    {
                        if (e.Orders.Any())
                        {
                            return Ok(new
                            {
                                result = 0,
                                message = "Error"
                            });
                        }
                        _employeeRepository.Delete(e);

                        return Ok(new
                        {
                            result = e.Id,
                            message = "Success"
                        });
                    }
                }
            }
            catch (Exception e)
            {
                Debug.WriteLine(e);
            }
            return InternalServerError();
        }

    }

    public class GetEmployeeParameter
    {
        public int EmployeeId { get; set; }
        public int Page { get; set; }
        public int PharmacyId { get; set; }
        public string Search { get; set; }
        public int UserId { get; set; }
    }

    public class SaveEmployeeParameter
    {
        public int Id { get; set; }
        public string Address { get; set; }
        public int UserId { get; set; }
        public int PharmacyId { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public float Salary { get; set; }
        public float DutyHours { get; set; }
    }
}

FYPWeb/Controllers/Api/NotificationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Http;
using FYPWeb.Repository.Repository;

namespace FYPWeb.Controllers.Api
{
    public class NotificationController : ApiController
    {
        private readonly NotificationRepository _notificationRepository;
        public NotificationController(NotificationRepository notificationRepository)
        {
            _notificationRepository = notificationRepository;
        }
        public IHttpActionResult GetNotificationAdmin([FromBody] GetNotificationParameter parameter)
        {
            if (parameter.Id > 0)
            {
                   
            }
            return Ok(new
            {
                result = "",
                message = "Error : Id incorrect"
            });
        }
        [HttpPost]
        public IHttpActionResult GetNotificationUnSeenCount([FromBody] GetNotificationParameter parameter)
        {
            var i = 0;
            if (parameter.UserId > 0)
            {
                i = _notificationRepository.GetUnSeenCountByUserId(parameter.UserId);
            }
            return Ok(new
            {
                result = i,
                message = "Success"
            });
        }
    }

    public class GetNotificationParameter
    {
        public int Id { get; set; }
        public int UserId { get; set; }
    }
}

FYPWeb/Controllers/MedicineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FYPWeb.Repository.Repository;
using FYPWeb.Service;
using FYPWeb.ViewModels;

namespace FYPWeb.Controllers
{
    public class MedicineController : Controller
    {
        private readonly DrugCartRepository _drugCartRepository;
        private readonly DrugReviewRepository _drugReviewRepository;
        private readonly DrugRepository _drugRepository;
        private readonly PharmacyRepository _pharmacyRepository;
        private readonly PromotionRepository _promotionRepository;
        private readonly RecommendationRepository _recommendationRepository;
        private readonly InventoryTrackRepository _inventoryTrackRepository;
        public MedicineController(DrugCartRepository drugCartRepository, DrugReviewRepository drugReviewRepository, DrugRepository drugRepository, PharmacyRepository pharmacyRepository, PromotionRepository promotionRepository, RecommendationRepository recommendationRepository, InventoryTrackRepository inventoryTrackRepository)
        {
            _drugCartRepository = drugCartRepository;
            _drugReviewRepository = drugReviewRepository;
            _drugRepository = drugRepository;

            _pharmacyRepository = pharmacyRepository;
            _promotionRepository = promotionRepository;
            _recommendationRepository = recommendationRepository;
            _inventoryTrackRepository = inventoryTrackRepository;
        }

        public ActionResult Index(int id)
        {
            var isReview = false;
            var i = 0;
            if (SessionService.UserId != "")
            {
                i = _drugCartRepository.GetUniqueMedicineCountByUserId(int.Parse(SessionService.UserId));
                isReview = _drugReviewRepository.IsReviewed(id, int.Parse(SessionService.UserId));
            }

            var m = _drugRepository.GetById(id);
            if (m != null)
            {
                m.PageVisit++;
                _drugRepository.Update(m);
                var d = new HomeMedicineViewModel()
                {
                    Drug = m,
                    HeaderViewModel = new HomeHeaderViewModel()
                    {
                        Header = HomeHeader.None,
                        CartCount = i,
                        NotificationCount = 0,
                    },
                    IsReviewed = isReview,
                    Rating = _drugReviewRepository.GetAverageReview(id),
                    ReviewPageCount = _drugReviewRepository.GetPaginationCountByMedicineId(id),
                    TotalReview = _drugReviewRepository.GetTotalCountByMedicineId(id),
                    DrugReviews = _drugReviewRepository.GetByMedicineId(id),
                    Pharmacies = _pharmacyRepository.GetPharmaciesByStockMedicineId(id),
                    RecommendationCount = _recommendationRepository.GetUniqueRecommendationByMedicineId(m.Id),
                    Prices = _inventoryTrackRepository.GetByDrugId(id)
                };
                return View("Index", d);
            }
            return RedirectToAction("Index", "Error");
        }
    }
}

FYPWeb/Controllers/ProfileController.cs
using System;
using System.Diagnostics;
using System.Linq;
using System.Web.Mvc;
using FYPWeb.Repository.Repository;
using FYPWeb.Service;
using FYPWeb.ViewModels;

namespace FYPWeb.Controllers
{
    public class ProfileController : Controller
    {
        private readonly UserRepository _userRepository;
        private readonly PharmacyRepository _pharmacyRepository;
        private readonly DrugCartRepository _drugCartRepository;
        private readonly PharmacistReviewRepository _pharmacistReviewRepository;
        private readonly InventoryTrackRepository _inventoryRepository;
        public ProfileController(UserRepository userRepository, PharmacyRepository pharmacyRepository, DrugCartRepository drugCartRepository, PharmacistReviewRepository pharmacistReviewRepository, InventoryTrackRepository inventoryRepository)
        {
            _userRepository = userRepository;
            _pharmacyRepository = pharmacyRepository;
            _drugCartRepository = drugCartRepository;
            _pharmacistReviewRepository = pharmacistReviewRepository;
            _inventoryRepository = inventoryRepository;
        }

        public ActionResult Index(string username,int page = 1)
        {
            try
            {
                int c = 0;
                if (SessionService.UserId != "")
                {
                    c = _drugCartRepository.GetUniqueMedicineCountByUserId(int.Parse(SessionService.UserId));
                }
                var user = _userRepository.GetByUsername(username);
                if (user != null)
                {
                    if (user.UserRoleId == 2)
                    {
                        var m = new HomeProfileViewModel()
                        {
                            User = user,
                            HeaderViewModel = new HomeHeaderViewModel()
                            {
                                Header = HomeHeader.None,
                                CartCount = c,
                            },
                        };
                        return View("CustomerProfile", m);
                    }
                    else if(user.UserRoleId == 3)
                    {
                        var m = new HomeProfileViewModel()
                        {
                            User = user,
                            HeaderViewModel = new HomeHeaderViewModel()
                            {
                                Header = HomeHeader.None,
                                CartCount = c,
                            },
                            Pharmacy = _pharmacyRepository.GetApprovedPharmaciesByUserId(user.Id).FirstOrDefault(),
                        };
                        if (m.Pharmacy != null)
                        {
                            m.InventoryTracks = _inventoryRepository.GetDrugsByPharmacyId(m.Pharmacy.Id,page,12);
                            m.Page = page;
                            m.PageCount = _inventoryRepository.GetDrugsByPharmacyIdCount(m.Pharmacy.Id, 12);
                        }
                        return View("PharmacistProfile", m);
                    }
                }
            }
            catch (Exception e)
            {
                Debug.WriteLine(e);
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

FYPWeb/Views/Pharmacist/Recommendation.cshtml
@using FYPWeb.Service
@using FYPWeb.ViewModels
@model PharmacistDashboardRecommendationViewModel
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@SessionService.FullName | @SessionService.UserRole Dashboard</title>
    <!-- Tell the browser to be responsive to screen width -->
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="~/Assets/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Assets/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="~/Assets/bower_components/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Assets/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="~/Assets/dist/css/skins/_all-skins.min.css">
    <!-- Morris chart -->
    <link rel="stylesheet" href="~/Assets/bower_components/morris.js/morris.css">
    <!-- jvectormap -->
    <link rel="stylesheet" href="~/Assets/bower_components/jvectormap/jquery-jvectormap.css">
    <!-- Date Picker -->
    <link rel="stylesheet" href="~/Assets/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="~/Assets/bower_components/bootstrap-daterangepicker/daterangepicker.css">
    <link rel="stylesheet" href="~/Assets/bower_components/dropzone/dropzone.css">
    <link rel="stylesheet" href="~/Assets/bower_components/toastr/toastr.css">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="~/Assets/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/Assets/plugins/iCheck/square/blue.css">
    <link rel="stylesheet" href="~/Assets/bower_components/select2/dist/css/select2.min.css">


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-green sidebar-mini">
    <div class="wrapper">


        @{
            Html.RenderPartial("Header", Model.PharmacistHeaderViewModel);
        }
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    Dashboard
                    <small>Control panel</small>
                </h1>
            </section>

            <!-- Main content -->
            <section class="content">
                <div class="row">
                    <div class="col-md-12">
                        <div class="box">
                            <div class="box-header">
                                <h3 class="box-title">Recommendation @(Model.PharmacistHeaderViewModel.Header == PharmacistHeader.RecommendationRecieved ? "Recieved" : "Sent")</h3>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body">
                                <div class="row">
                                    <div class="col-xs-12">
                                        <table class="table table-bordered table-striped">
                                            <thead>
                                                <tr>
                                                    <th>Drug</th>
                                                    <th>To User</th>
                                                    <th>From</th>
                                                    <th>Recommended At</th>
                                                </tr>
                                            </thead>
                                            <tbody id="recommendationTable">
                                                @foreach (var m in Model.Recommendations)
                                                {
                                                    <tr>
                                                        <td>
                                                            <a href="@Url.Action("Index","Medicine",new { id = m.DrugId})">@m.Drug.DrugName</a>
                                                        </td>
                                                        <td>
                                                            <a href="@Url.Action("Index","Profile",new { username = m.ToUser.Username})">@m.ToUser.ToString()</a>
                                                        </td>
                                                        <td>
                                                            <a href="@Url.Action("Index","Profile",new { username = m.FromUser.Username})">@m.FromUser.ToString()</a>
                                                        </td>
                                                        <td>
                                                            @m.RecommendedAt
                                                        </td>
                                                    </tr>
                                                }
                                            </tbody>

                                        </table>
                                        <div id="overlay"></div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-xs-12">
                                        <ul class="pagination">
                                            @if (Model.Page > 1)
                                            {
                                                <li>
                                                    <a href="@Url.Action("Recommendation", "Pharmacist", new {parameter = Model.Parameter, page = 1,type = Model.Type})"><< First</a>
                                                </li>
                                                <li>
                                                    <a href="@Url.Action("Recommendation", "Pharmacist", new {parameter = Model.Parameter,type = Model.Type, page = Model.Page - 1})">< Prev</a>
                                                </li>
                                            }
                                            <li class="active">
                                                <a href="@Url.Action("Recommendation", "Pharmacist", new {parameter = Model.Parameter,type = Model.Type, page = Model.Page})">@Model.Page</a>
                                            </li>
                                            @if (Model.Page + 1 <= Model.PageCount)
                                            {
                                                <li class="">
                                                    <a href="@Url.Action("Recommendation", "Pharmacist", new {parameter = Model.Parameter,type = Model.Type, page = Model.Page + 1})">@(Model.Page + 1)</a>
                                                </li>
                                            }
                                            @if (Model.Page + 2 <= Model.PageCount)
                                            {
                                                <li class="">
                                                    <a href="@Url.Action("Recommendation", "Pharmacist", new {parameter = Model.Parameter,type = Model.Type, page = Model.Page + 2})">@(Model.Page + 2)</a>
                                                </li>
                                            }
                                            @if (Model.Page < Model.PageCount)
                                            {
                                                <li>
                                                    <a href="@Url.Action("Recommendation", "Pharmacist", new {parameter = Model.Parameter,type = Model.Type, page = Model.Page + 1})">Next ></a>
                                                </li>
                                                <li>
                                                    <a href="@Url.Action("Recommendation", "Pharmacist", new {parameter = Model.Parameter,type = Model.Type, page = Model.PageCount})">Last >></a>
                                                </li>
                                            }
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <!-- /.box-body -->
                        </div>
                    </div>
                </div>
            </section>
            <!-- /.content -->
        </div>

        <!-- /.content-wrapper -->
        @{
            Html.RenderPartial("Footer");
        }
    </div>
    <!-- ./wrapper -->
    <!-- jQuery 3 -->
    <script src="~/Assets/bower_components/jquery/dist/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
<script src="~/Assets/bower_components/jquery-ui/jquery-ui.min.js"></script>
    <script src="~/Scripts/jquery.signalR-2.2.3.min.js"></script>
    <script src="~/signalr/js"></script>

    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button);
    </script>
    <!-- Bootstrap 3.3.7 -->
    <script src="~/Assets/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- Morris.js charts -->
    <script src="~/Assets/bower_components/raphael/raphael.min.js"></script>
    <script src="~/Assets/bower_components/morris.js/morris.min.js"></script>
    <!-- Sparkline -->
    <script src="~/Assets/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js"></script>
    <!-- jvectormap -->
    <script src="~/Assets/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
    <script src="~/Assets/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="~/Assets/bower_components/jquery-knob/dist/jquery.knob.min.js"></script>
    <!-- daterangepicker -->
    <script src="~/Assets/bower_components/moment/min/moment.min.js"></script>
    <script src="~/Assets/bower_components/bootstrap-daterangepicker/daterangepicker.js"></script>
    <!-- datepicker -->
    <script src="~/Assets/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
    <!-- Bootstrap WYSIHTML5 -->
    <script src="~/Assets/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
    <!-- Slimscroll -->
    <script src="~/Assets/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="~/Assets/bower_components/fastclick/lib/fastclick.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Assets/dist/js/adminlte.min.js"></script>
    <!-- DataTables -->
    <script src="~/Assets/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="~/Assets/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="~/Assets/plugins/iCheck/icheck.min.js"></script>
    <script src="~/Assets/bower_components/jquery-inputmask/jquery.inputmask.bundle.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Assets/bower_components/dropzone/dropzone.js"></script>

    <script>
        var userId = @SessionService.UserId;
        var type =
            '@(Model.PharmacistHeaderViewModel.Header == PharmacistHeader.RecommendationRecieved ? "recieved" : "sent")';
    </script>
    <!-- Page script -->
    <script src="~/Assets/bower_components/toastr/toastr.js"></script>
    <script src="~/Assets/bower_components/select2/dist/js/select2.full.min.js"></script>
<script src="~/Assets/Assets/js/util.js"></script>
    <script src="~/Assets/Assets/js/signalRLib.js"></script>
    <script>
    $(function() {
        @if (SessionService.UserId != "")
        {
            @:startSignalR('@SessionService.GetClientId()');
        }
    });

    </script>

</body>
</html>