FYPWeb/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FYPWeb.Repository.Repository;
using FYPWeb.Service;
using FYPWeb.ViewModels;
using Model.Entity;

namespace FYPWeb.Controllers
{
    public class CartController : Controller
    {
        private readonly DrugCartRepository _drugCartRepository;
        private readonly PharmacyRepository _pharmacyRepository;
        private readonly SessionCartRepository _sessionCartRepository;
        private readonly InventoryTrackRepository _inventoryTrackRepository;
        public CartController(DrugCartRepository drugCartRepository, PharmacyRepository pharmacyRepository, SessionCartRepository sessionCartRepository, PharmacyRepository pharmacyRepository1, InventoryTrackRepository inventoryTrackRepository)
        {
            _drugCartRepository = drugCartRepository;
            _sessionCartRepository = sessionCartRepository;
            _pharmacyRepository = pharmacyRepository1;
            _inventoryTrackRepository = inventoryTrackRepository;
        }

        public ActionResult Index()
        {
            if (SessionService.UserId == "Pharmacist")
                return RedirectToAction("Index", "Home");

            if (SessionService.UserId != "")
            {
                var id = int.Parse(SessionService.UserId);

                var d = new HomeCartViewModel()
                {
                    HeaderViewModel = new HomeHeaderViewModel()
                    {
                        Header = HomeHeader.None,
                        CartCount = _drugCartRepository.GetUniqueMedicineCountByUserId(id),
                        NotificationCount = 0,
                    },
                    DrugCarts = _drugCartRepository.GetByUserId(id),
                };
                if (d.DrugCarts.Any())
                {
                    var listOfSelected =
                        d.DrugCarts.GroupBy(p => p.Inventory.PharmacyId)
                            .Select(p => p.FirstOrDefault().Inventory.Pharmacy);
                    d.Pharmacies = listOfSelected;
                }
                return View("Index", d);
            }
            else
            {
                var d = new HomeCartViewModel()
                {
                    HeaderViewModel = new HomeHeaderViewModel()
                    {
                        Header = HomeHeader.None,
                        CartCount = _sessionCartRepository.GetUniqueMedicineCountBySessionId(SessionService.SessionId),
                        NotificationCount = 0,
                    },
                    DrugCarts = _sessionCartRepository.GetBySessionId(SessionService.SessionId).Select(p => new DrugCart()
                    {
                        InventoryId = p.InventoryId,
                        Inventory = p.Inventory,
                        Quantity = p.Quantity,
                    }),
                };
                if (d.DrugCarts.Any())
                {
                    var listOfSelected =
                        d.DrugCarts.GroupBy(p => p.Inventory.PharmacyId)
                            .Select(p => p.FirstOrDefault().Inventory.Pharmacy);
                    d.Pharmacies = listOfSelected;
                }
                return View("Index", d);

            }
        }
    }
}

FYPWeb/Controllers/ForumController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web.Mvc;
using FYPWeb.Enum;
using FYPWeb.Hub;
using FYPWeb.Repository.Repository;
using FYPWeb.Service;
using FYPWeb.ViewModels;
using Model.Entity;

namespace FYPWeb.Controllers
{
    public class ForumController : Controller
    {
        private readonly PostThreadRepository _postThreadRepository;
        private readonly TagPostThreadRepository _tagPostThreadRepository;
        private readonly PostCategoryRepository _postCategoryRepository;
        private readonly PostReplyRepository _postReplyRepository;
        private readonly TagRepository _tagRepository;
        private readonly NotificationRepository _notificationRepository;
        public ForumController(DrugCartRepository drugCartRepository, PostCategoryRepository postCategoryRepository, PostThreadRepository postThreadRepository, PostReplyRepository postReplyRepository, TagPostThreadRepository tagPostThreadRepository, TagRepository tagRepository, NotificationRepository notificationRepository)
        {
            _postCategoryRepository = postCategoryRepository;
            _postThreadRepository = postThreadRepository;
            _postReplyRepository = postReplyRepository;
            _tagPostThreadRepository = tagPostThreadRepository;
            _tagRepository = tagRepository;
            _notificationRepository = notificationRepository;
        }

        public ActionResult Index()
        {
            var m = new ForumIndexViewModel()
            {
                Header = new ForumHeaderViewModel()
                {
                    Header = HomeHeader.Forum
                },
                PostThreads = _postThreadRepository.GetLatestThreads(1,5),
                Categories = _postCategoryRepository.GetTopCategories(1,5),
                HotPostThreads = _postThreadRepository.GetHotThreads(5)

            };
            return View("Index", m);
        }

        [HttpGet]
        public ActionResult AllThreadPost(string parameter = "", int page = 1)
        {
            try
            {
                if (page < 1)
                {
                    page = 1;
                }
                var m = new ForumAllThreadPostViewModel()
                {
                    Header = new ForumHeaderViewModel()
                    {
                        Header = HomeHeader.Forum
                    },
                    Page = page,
                    Parameter = parameter,
                };
                if (string.IsNullOrEmpty(parameter))
                {
                    m.PostThreads = _postThreadRepository.GetLatestThreads(page);
                    m.PageCount = _postThreadRepository.GetPaginationCount(10);
                }
                else
                {
                    m.PostThreads = _postThreadRepository.GetLatestThreads(parameter, page);
                    m.PageCount = _postThreadRepository.GetPaginationSearchCount(parameter, 10);
                }
                return View("AllThreadPost", m);
            }
            catch (Exception e)
            {
                Debug.WriteLine(e);
            }
            return RedirectToAction("Index", "Forum");
        }


        [HttpGet]
        public ActionResult AllTags(string parameter = "", int page = 1)
        {
            try
            {
                if (page < 1)
                {
                    page = 1;
                }
                var m = new ForumAllTagsViewModel()
                {
                    Header = new ForumHeaderViewModel()
                    {
                        Header = HomeHeader.Forum
                    },
                    Page = page,
                    Parameter = parameter,
                };
                if (string.IsNullOrEmpty(parameter))
                {
                    m.Tags = _tagRepository.GetAllTags(page);
                    m.PageCount = _tagRepository.GetPaginationCount();
                }
                else
                {
                    m.Tags = _tagRepository.GetAllTagsSearch(parameter,page);
                    m.PageCount = _tagRepository.GetPaginationSearchCount(parameter);
                }
                return View("AllTag", m);
            }
            catch (Exception e)
            {
                Debug.WriteLine(e);
            }
            return RedirectToAction("Index", "Forum");
        }

        [HttpGet]
        public ActionResult AllCategories(string parameter = "", int page = 1)
        {
            try
            {
                if (page < 1)
                {
                    page = 1;
                }
                var m = new ForumAllCategoriesViewModel()
                {
                    Header = new ForumHeaderViewModel()
                    {
                        Header = HomeHeader.Forum
                    },
                    Page = page,
                    Parameter = parameter,
                };
                if (string.IsNullOrEmpty(parameter))
                {
                    m.PostCategories = _postCategoryRepository.GetCategories(page);
                    m.PageCount = _postCategoryRepository.GetPaginationCount();
                }
                else
                {
                    m.PostCategories = _postCategoryRepository.GetCategoriesSearch(parameter,page);
                    m.PageCount = _postCategoryRepository.GetPaginationSearchCount(parameter);
                }
                return View("AllCategories", m);
            }
            catch (Exception e)
            {
                Debug.WriteLine(e);
            }
            return RedirectToAction("Index", "Forum");
        }

        [HttpGet]
        public ActionResult AllThreadPostByTag(string tag = "", int page = 1)
        {
            try
            {
                if (page < 1)
                {
                    page = 1;
                }
                var m = new ForumAllThreadPostViewModel()
                {
                    Header = new ForumHeaderViewModel()
                    {
                        Header = HomeHeader.Forum
                    },
                    Page = page,
                    Tag = tag,
                };
                if (!string.IsNullOrEmpty(tag))
                {
                    m.PostThreads = _postThreadRepository.GetLatestThreadsByTag(tag,page);
                    m.PageCount = _postThreadRepository.GetPaginationCountByTag(tag,10);
                    return View("AllThreadPostByTag", m);
                }
            }
            catch (Exception e)
            {
                Debug.WriteLine(e);
            }
            return RedirectToAction("Index", "Forum");
        }
        [HttpGet]
        public ActionResult AllThreadPostByCategory(int catId = 0, int page = 1)
        {
            try
            {
                if (page < 1)
                {
                    page = 1;
                }
                var m = new ForumAllThreadPostViewModel()
                {
                    Header = new ForumHeaderViewModel()
                    {
                        Header = HomeHeader.Forum
                    },
                    Page = page,
                };
                if (catId > 0)
                {
                    m.Category = _postCategoryRepository.GetById(catId)?.CategoryName;
                    m.PostThreads = _postThreadRepository.GetLatestThreadsByCategory(catId, page);
                    m.PageCount = _postThreadRepository.GetPaginationCountByCategory(catId, 10);
                    return View("AllThreadPostByCategory", m);
                }
            }
            catch (Exception e)
            {
                Debug.WriteLine(e);
            }
            return RedirectToAction("Index", "Forum");
        }

        [HttpGet]
        public ActionResult PostThread(int id, int page = 1)
        {
            try
            {
                if (id > 0)
                {
                    var p = _postThreadRepository.GetById(id);
                    if (p != null)
                    {
                        var pCount = _postReplyRepository.GetPaginationCountByPostId(p.Id);
                        var m = new ForumPostThreadViewModel()
                        {
                            Header = new ForumHeaderViewModel()
                            {
                                Header = HomeHeader.Forum
                            },
                            PostThread = p,
                            CurrentPage = page,
                            Page = pCount,
                            Tags = _tagPostThreadRepository.GetTagsByPostId(p.Id)
                        };
                        return View("PostThread", m);
                    }
                }
            }
            catch (Exception e)
            {
                Debug.WriteLine(e);
            }
            return RedirectToAction("Index", "Forum");
        }

        public ActionResult EditPost(int id)
        {
            try
            {
                if (SessionService.UserId != "")
                {
                    var p = _postThreadRepository.GetById(id);
                    if (p != null && p.UserId + "" == SessionService.UserId)
                    {
                        var m = new ForumEditPostViewModel()
                        {
                            Header = new ForumHeaderViewModel()
                            {
                                Header = HomeHeader.Forum
                            },
                            PostCategories = _postCategoryRepository.GetAll(),
                            PostThread = p
                        };
                        return View("EditPost", m);
                    }
                }
            }
            catch (Exception e)
            {
                Debug.WriteLine(e);
            }

FYPWeb/Controllers/ProfileController.cs
using System;
using System.Diagnostics;
using System.Linq;
using System.Web.Mvc;
using FYPWeb.Repository.Repository;
using FYPWeb.Service;
using FYPWeb.ViewModels;

namespace FYPWeb.Controllers
{
    public class ProfileController : Controller
    {
        private readonly UserRepository _userRepository;
        private readonly PharmacyRepository _pharmacyRepository;
        private readonly DrugCartRepository _drugCartRepository;
        private readonly PharmacistReviewRepository _pharmacistReviewRepository;
        private readonly InventoryTrackRepository _inventoryRepository;
        public ProfileController(UserRepository userRepository, PharmacyRepository pharmacyRepository, DrugCartRepository drugCartRepository, PharmacistReviewRepository pharmacistReviewRepository, InventoryTrackRepository inventoryRepository)
        {
            _userRepository = userRepository;
            _pharmacyRepository = pharmacyRepository;
            _drugCartRepository = drugCartRepository;
            _pharmacistReviewRepository = pharmacistReviewRepository;
            _inventoryRepository = inventoryRepository;
        }

        public ActionResult Index(string username,int page = 1)
        {
            try
            {
                int c = 0;
                if (SessionService.UserId != "")
                {
                    c = _drugCartRepository.GetUniqueMedicineCountByUserId(int.Parse(SessionService.UserId));
                }
                var user = _userRepository.GetByUsername(username);
                if (user != null)
                {
                    if (user.UserRoleId == 2)
                    {
                        var m = new HomeProfileViewModel()
                        {
                            User = user,
                            HeaderViewModel = new HomeHeaderViewModel()
                            {
                                Header = HomeHeader.None,
                                CartCount = c,
                            },
                        };
                        return View("CustomerProfile", m);
                    }
                    else if(user.UserRoleId == 3)
                    {
                        var m = new HomeProfileViewModel()
                        {
                            User = user,
                            HeaderViewModel = new HomeHeaderViewModel()
                            {
                                Header = HomeHeader.None,
                                CartCount = c,
                            },
                            Pharmacy = _pharmacyRepository.GetApprovedPharmaciesByUserId(user.Id).FirstOrDefault(),
                        };
                        if (m.Pharmacy != null)
                        {
                            m.InventoryTracks = _inventoryRepository.GetDrugsByPharmacyId(m.Pharmacy.Id,page,12);
                            m.Page = page;
                            m.PageCount = _inventoryRepository.GetDrugsByPharmacyIdCount(m.Pharmacy.Id, 12);
                        }
                        return View("PharmacistProfile", m);
                    }
                }
            }
            catch (Exception e)
            {
                Debug.WriteLine(e);
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

FYPWeb/Views/Forum/Footer.cshtml
<footer class="main-footer">
    <div class="container">
        <div class="pull-right hidden-xs">
            <b>Version</b> 1.0.0
        </div>
        <strong>Copyright &copy; 2017-2018 <a href="">Dusk Lord</a>.</strong> All rights
        reserved.
    </div>
    <!-- /.container -->
</footer>

FYPWeb/Views/Forum/Header.cshtml
@using FYPWeb.Service
@using FYPWeb.ViewModels
@model FYPWeb.ViewModels.ForumHeaderViewModel
<header class="main-header">
    <nav class="navbar navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <a href="@Url.Action("Index","Home")" class="navbar-brand">
                    <span class="logo-mini">
                        <img src="~/Assets/Assets/img/OMDM-logo-horizontal-small.png" width="100" class="img-responsive">
                    </span>
                </a>
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#navbar-collapse">
                    <i class="fa fa-bars"></i>
                </button>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse pull-left" id="navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="@(Model.Header == HomeHeader.Home ? "active": "")"><a href="@Url.Action("Index","Home")">Home <span class="sr-only">(current)</span></a></li>
                    <li class="@(Model.Header == HomeHeader.AboutUs ? "active": "")"><a href="#">About Us</a></li>
                    <li class="@(Model.Header == HomeHeader.ContactUs ? "active": "")"><a href="#">Contact Us</a></li>
                    <li class="@(Model.Header == HomeHeader.Forum ? "active": "")"><a href="@Url.Action("Index","Forum")">Forum</a></li>
                    <li class="@(Model.Header == HomeHeader.PharmacyNearMe ? "active": "")"><a href="@Url.Action("PharmacyNearYou","Home")">Pharmacy Near Me</a></li>
                </ul>
                <form class="navbar-form navbar-left" role="search" action="/Search">
                    <div class="form-group">
                        <input type="text" class="form-control" id="searchAll" name="q" placeholder="Search" onkeypress="return searchAll(e)">
                        <select class="form-control" id="searchType" name="type">
                            <option value="1">Medicine</option>
                            <option value="3">Company</option>
                            <option value="2">Disease</option>
                            <option value="4">Categories</option>
                            <option value="5">Posts</option>
                            <option value="6">Tags</option>
                            <option value="7">Users</option>
                            <option value="8">Pharmacies</option>
                        </select>
                    </div>
                </form>
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Browse <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="@Url.Action("AllMedicine", "Home")">Medicines</a></li>
                            <li><a href="@Url.Action("AllDisease", "Home")">Disease</a></li>
                            <li><a href="@Url.Action("AllCompanies", "Home")">Company</a></li>
                            <li><a href="@Url.Action("AllTags", "Forum")">Tags</a></li>
                            <li><a href="@Url.Action("AllCategories", "Forum")">Categories</a></li>
                            <li><a href="@Url.Action("AllThreadPost", "Forum")">Posts</a></li>
                            <li><a href="@Url.Action("AllUsers", "Home")">Users</a></li>
                            <li><a href="@Url.Action("AllPharmacies", "Home")">Pharmacies</a></li>
                        </ul>
                    </li>
                    @if (SessionService.UserId == "")
                    {
                        <li><a href="@Url.Action("Login", "Home")">Login</a></li>
                        <li><a href="@Url.Action("Register", "Home")">Sign Up</a></li>
                    }
                </ul>
            </div>
            <!-- /.navbar-collapse -->
            <!-- Navbar Right Menu -->
            @if (SessionService.UserId != "")
            {
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- Messages: style can be found in dropdown.less-->
                        <!-- /.messages-menu -->
                        <!-- Notifications Menu -->
                       @if(SessionService.UserRole != "Pharmacist") { 
                           <li>
                               <a href="@Url.Action("Index","Cart")">
                                   <i class="fa fa-shopping-cart"></i>
                                   <span class="label label-warning" id="cartCount">@Model.CartCount</span>
                               </a>
                           </li>
                       }
                        <li class="dropdown notifications-menu">
                            <!-- Menu toggle button -->
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" onclick="goToUrl('@Url.Action("Message","Home")')">
                                <i class="fa fa-envelope"></i>
                                <span class="label label-warning" id="messageCount">0</span>
                            </a>
                        </li>
                        <li class="dropdown notifications-menu">
                            <!-- Menu toggle button -->
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" onclick="getNotification(this,@SessionService.UserId)">
                                <i class="fa fa-bell-o"></i>
                                <span class="label label-warning" id="notificationCount">10</span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <!-- Inner Menu: contains the notifications -->
                                    <ul class="menu" id="notificationList">
                                        <li>
                                            <!-- start notification -->
                                            <a href="#">
                                                <i class="fa fa-users text-aqua"></i> 5 new members joined today
                                            </a>
                                        </li>
                                        <!-- end notification -->
                                    </ul>
                                </li>
                                <li class="footer"><a href="@(SessionService.UserRole.Contains("Customer") ? Url.Action("Notification","Customer") : Url.Action("Notification","Pharmacist"))">View all</a></li>
                            </ul>
                        </li>
                        <!-- Tasks Menu -->
                        <!-- User Account Menu -->
                        <li class="dropdown user user-menu">
                            <!-- Menu Toggle Button -->
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <!-- The user image in the navbar-->
                                <img src="@SessionService.UserImage" class="user-image" alt="User Image">
                                <!-- hidden-xs hides the username on small devices so only the image appears. -->
                                <span class="hidden-xs">@SessionService.FullName</span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- The user image in the menu -->
                                <li class="user-header">
                                    <img src="@SessionService.UserImage" class="img-circle" alt="User Image">

                                    <p>
                                        @SessionService.FullName - @SessionService.UserRole
                                        <small>Member since Jan. 2018</small>
                                    </p>
                                </li>
                                <li class="user-body">
                                    <div class="row">
                                        <div class="col-xs-6 col-xs-push-3">
                                            @switch (SessionService.UserRole)
                                            {
                                                case "Admin":
                                                    <a href="@Url.Action("Index","Admin")" style="color:white !important" class="btn btn-primary btn-block">Dashboard</a>
                                                    break;
                                                case "Customer":
                                                    <a href="@Url.Action("Dashboard","Customer")" style="color:white !important" class="btn btn-primary btn-block">Dashboard</a>
                                                    break;
                                                case "Pharmacist":
                                                    <a href="@Url.Action("Dashboard","Pharmacist")" style="color:white !important" class="btn btn-primary btn-block">Dashboard</a>
                                                    break;
                                            }
                                        </div>
                                    </div>
                                </li>
                                <!-- Menu Body -->
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="row">
                                        <div class="col-xs-6 text-center">
                                            @switch (SessionService.UserRole)
                                            {
                                                case "Admin":
                                                    <a href="@Url.Action("","Admin")" class="btn btn-default btn-flat">Profile</a>
                                                    break;
                                                case "Customer":
                                                    <a href="@Url.Action("MyProfile","Customer")" class="btn btn-default btn-flat">Profile</a>
                                                    break;
                                                case "Pharmacist":
                                                    <a href="@Url.Action("MyProfile","Customer")" class="btn btn-default btn-flat">Profile</a>
                                                    break;
                                            }
                                        </div>
                                        <div class="col-xs-6 text-center">
                                            <a href="@Url.Action("LogOut","Home")" class="btn btn-default btn-flat">Log Out</a>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <!-- /.navbar-custom-menu -->
            }
        </div>
        <!-- /.container-fluid -->
    </nav>
</header>