FYPWeb/ViewModels/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using FYPWeb.Controllers;

namespace FYPWeb.ViewModels
{
    public class LoginViewModel
    {
        public string Message { get; set; }
    }

    public class RegisterViewModel
    {
        public string Message { get; set; }
        public RegisterUserParameter Parameter { get; set; }
    }

}

FYPWeb/ViewModels/SendEmailViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FYPWeb.ViewModels
{
    public class SendEmailViewModel
    {
        public string Email { get; set; }
        public string Name { get; set; }
    }
}

FYPWeb/Controllers/Api/MessageController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Http;
using FYPWeb.Repository.Repository;

namespace FYPWeb.Controllers.Api
{
    public class MessageController : ApiController
    {
        private readonly MessageRepository _messageRepository;

        public MessageController(MessageRepository messageRepository)
        {
            _messageRepository = messageRepository;
        }

        [HttpPost]
        public IHttpActionResult GetMessagesByOrderId([FromBody] GetMessagesByOrderIdParameter parameter)
        {
            try
            {
                if (parameter != null && parameter.OrderId > 0 && parameter.Page > 0)
                {
                    var list = _messageRepository.GetMany(p => p.OrderId == parameter.OrderId, parameter.Page, 10,
                        p => p.CreatedOn, true).ToList().Select(p => new
                    {
                        name = p.SenderUser.ToString(),
                        picture = p.SenderUser.UserImage,
                        content = p.Content,
                        date = p.CreatedOn,
                        sId = p.SenderUserId,
                        rId = p.RecieverUserId
                    });

                    return Ok(new
                    {
                        result = list,
                        message = "Success"
                    });
                }
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex);
            }
            return InternalServerError();
        }
    }

    public class GetMessagesByOrderIdParameter
    {
        public int OrderId { get; set; }
        public int Page { get; set; }
    }
}

FYPWeb/Controllers/BrandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FYPWeb.Repository.Repository;
using FYPWeb.Service;
using FYPWeb.ViewModels;

namespace FYPWeb.Controllers
{
    public class BrandController : Controller
    {
        private readonly DrugCartRepository _drugCartRepository;
        private readonly BrandRepository _brandRepository;

        public BrandController(DrugCartRepository drugCartRepository, BrandRepository brandRepository)
        {
            _drugCartRepository = drugCartRepository;
            _brandRepository = brandRepository;
        }

        public ActionResult Index(int id)
        {
            var b = _brandRepository.GetById(id);
            if (b == null) return RedirectToAction("Index", "Home");
            var i = 0;
            if (SessionService.UserId != "")
            {
                i = _drugCartRepository.GetUniqueMedicineCountByUserId(int.Parse(SessionService.UserId));
            }
            var model = new BrandProfileViewModel()
            {
                Brand = b,
                HeaderViewModel = new HomeHeaderViewModel()
                {
                    Header = HomeHeader.None,
                    CartCount = i,
                    NotificationCount = 0,
                }
            };
            return View("Index", model);
        }
    }
}

FYPWeb/Controllers/CompanyController.cs
using System.Web.Mvc;
using FYPWeb.Repository.Repository;
using FYPWeb.Service;
using FYPWeb.ViewModels;

namespace FYPWeb.Controllers
{
    public class CompanyController : Controller
    {
        private readonly DrugCartRepository _drugCartRepository;
        private readonly CompanyRepository _companyRepository;
        public CompanyController(DrugCartRepository drugCartRepository, CompanyRepository companyRepository)
        {
            _drugCartRepository = drugCartRepository;
            _companyRepository = companyRepository;
        }

        public ActionResult Index(int id)
        {
            var c = _companyRepository.GetById(id);
            if (c == null) return RedirectToAction("Index", "Home");
            var i = 0;
            if (SessionService.UserId != "")
            {
                i = _drugCartRepository.GetUniqueMedicineCountByUserId(int.Parse(SessionService.UserId));
            }
            var model = new CompanyProfileViewModel()
            {
                Company = c,
                HeaderViewModel = new HomeHeaderViewModel()
                {
                    Header = HomeHeader.None,
                    CartCount = i,
                    NotificationCount = 0,
                }
            };
            return View("Index", model);

        }
    }
}

FYPWeb/Controllers/DiseaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FYPWeb.Repository.Repository;
using FYPWeb.Service;
using FYPWeb.ViewModels;

namespace FYPWeb.Controllers
{
    public class DiseaseController : Controller
    {
        private readonly DrugCartRepository _drugCartRepository;
        private readonly DiseaseRepository _diseaseRepository;
        private readonly DrugRepository _drugRepository;
        public DiseaseController(DiseaseRepository diseaseRepository, DrugCartRepository drugCartRepository, DrugRepository drugRepository)
        {
            _diseaseRepository = diseaseRepository;
            _drugCartRepository = drugCartRepository;
            _drugRepository = drugRepository;
        }

        public ActionResult Index(int id,int indPage = 1,int conPage = 1)
        {
            var d = _diseaseRepository.GetById(id);
            if (d == null) return RedirectToAction("Index", "Home");
            var i = 0;
            if (indPage < 1)
            {
                indPage = 1;
            }
            if (conPage < 1)
            {
                conPage = 1;
            }

            if (SessionService.UserId != "")
            {
                i = _drugCartRepository.GetUniqueMedicineCountByUserId(int.Parse(SessionService.UserId));
            }
            d.PageVisit++;
            _diseaseRepository.Update(d);
            var model = new DiseaseProfileViewModel()
            {
                Disease = d,
                Id = id,
                HeaderViewModel = new HomeHeaderViewModel()
                {
                    Header = HomeHeader.None,
                    CartCount = i,
                    NotificationCount = 0,
                },
                IndicationDrugs = _drugRepository.GetIndicationDrugsByDiseaseId(id,indPage,9),
                NonIndicationDrugs = _drugRepository.GetNonIndicationDrugsByDiseaseId(id,conPage, 9),
                IndPage = indPage,
                ConPage = conPage,
                ConPageCount = _drugRepository.GetNonIndicationDrugsByDiseaseIdCount(id, 9),
                IndPageCount = _drugRepository.GetIndicationDrugsByDiseaseIdCount(id, 9),
            };
            return View("Index", model);

        }
    }
}

FYPWeb/Controllers/ProfileController.cs
using System;
using System.Diagnostics;
using System.Linq;
using System.Web.Mvc;
using FYPWeb.Repository.Repository;
using FYPWeb.Service;
using FYPWeb.ViewModels;

namespace FYPWeb.Controllers
{
    public class ProfileController : Controller
    {
        private readonly UserRepository _userRepository;
        private readonly PharmacyRepository _pharmacyRepository;
        private readonly DrugCartRepository _drugCartRepository;
        private readonly PharmacistReviewRepository _pharmacistReviewRepository;
        private readonly InventoryTrackRepository _inventoryRepository;
        public ProfileController(UserRepository userRepository, PharmacyRepository pharmacyRepository, DrugCartRepository drugCartRepository, PharmacistReviewRepository pharmacistReviewRepository, InventoryTrackRepository inventoryRepository)
        {
            _userRepository = userRepository;
            _pharmacyRepository = pharmacyRepository;
            _drugCartRepository = drugCartRepository;
            _pharmacistReviewRepository = pharmacistReviewRepository;
            _inventoryRepository = inventoryRepository;
        }

        public ActionResult Index(string username,int page = 1)
        {
            try
            {
                int c = 0;
                if (SessionService.UserId != "")
                {
                    c = _drugCartRepository.GetUniqueMedicineCountByUserId(int.Parse(SessionService.UserId));
                }
                var user = _userRepository.GetByUsername(username);
                if (user != null)
                {
                    if (user.UserRoleId == 2)
                    {
                        var m = new HomeProfileViewModel()
                        {
                            User = user,
                            HeaderViewModel = new HomeHeaderViewModel()
                            {
                                Header = HomeHeader.None,
                                CartCount = c,
                            },
                        };
                        return View("CustomerProfile", m);
                    }
                    else if(user.UserRoleId == 3)
                    {
                        var m = new HomeProfileViewModel()
                        {
                            User = user,
                            HeaderViewModel = new HomeHeaderViewModel()
                            {
                                Header = HomeHeader.None,
                                CartCount = c,
                            },
                            Pharmacy = _pharmacyRepository.GetApprovedPharmaciesByUserId(user.Id).FirstOrDefault(),
                        };
                        if (m.Pharmacy != null)
                        {
                            m.InventoryTracks = _inventoryRepository.GetDrugsByPharmacyId(m.Pharmacy.Id,page,12);
                            m.Page = page;
                            m.PageCount = _inventoryRepository.GetDrugsByPharmacyIdCount(m.Pharmacy.Id, 12);
                        }
                        return View("PharmacistProfile", m);
                    }
                }
            }
            catch (Exception e)
            {
                Debug.WriteLine(e);
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

FYPWeb/Views/Home/AllBrand.cshtml
@using FYPWeb.Service
@using FYPWeb.ViewModels
@model AllBrandsViewModal
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>OMDM | All Brands</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="~/Assets/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Assets/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="~/Assets/bower_components/Ionicons/css/ionicons.min.css">
    <link rel="stylesheet" href="~/Assets/bower_components/slick/slick.css">
    <link rel="stylesheet" href="~/Assets/bower_components/slick/slick-theme.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Assets/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="~/Assets/dist/css/skins/_all-skins.min.css">
    <link rel="stylesheet" href="~/Assets/bower_components/toastr/toastr.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<!-- ADD THE CLASS layout-top-nav TO REMOVE THE SIDEBAR. -->
<body class="hold-transition skin-green layout-top-nav">
    <div class="wrapper">
        @{
            Html.RenderPartial("Header", Model.HeaderViewModel);
        }
        <!-- Full Width Column -->
        <div class="content-wrapper">
            <div class="container">
                <section class="content">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="box box-solid box-success">
                                <div class="box-header">
                                    All Medicines
                                </div>
                                <div class="box-body">
                                    <div class="row">
                                        <div class="col-xs-12">
                                            <ul class="pagination">
                                                @if (Model.Page > 1)
                                                {
                                                    <li>
                                                        <a href="@Url.Action("AllBrands", "Home", new { page = 1})"><< First</a>
                                                    </li>
                                                    <li>
                                                        <a href="@Url.Action("AllBrands", "Home", new { page = Model.Page - 1})">< Prev</a>
                                                    </li>
                                                }
                                                <li class="active">
                                                    <a href="@Url.Action("AllBrands", "Home", new { page = Model.Page})">@Model.Page</a>
                                                </li>
                                                @if (Model.Page + 1 <= Model.PageCount)
                                                {
                                                    <li class="">
                                                        <a href="@Url.Action("AllBrands", "Home", new { page = Model.Page + 1})">@(Model.Page + 1)</a>
                                                    </li>
                                                }
                                                @if (Model.Page + 2 <= Model.PageCount)
                                                {
                                                    <li class="">
                                                        <a href="@Url.Action("AllBrands", "Home", new { page = Model.Page + 2})">@(Model.Page + 2)</a>
                                                    </li>
                                                }
                                                @if (Model.Page < Model.PageCount)
                                                {
                                                    <li>
                                                        <a href="@Url.Action("AllBrands", "Home", new { page = Model.Page + 1})">Next ></a>
                                                    </li>
                                                    <li>
                                                        <a href="@Url.Action("AllBrands", "Home", new { page = Model.PageCount})">Last >></a>
                                                    </li>
                                                }
                                            </ul>
                               </div>
                                    </div>
                                    @foreach (var modelBrand in Model.Brands)
                                    {
                                        <div class="row" style="cursor: pointer" onclick="goToUrl('@Url.Action("Index","Brand",new {id = modelBrand.Id})')">
                                            <div class="col-xs-12">
                                                <div class="panel panel-default">
                                                    <div class="panel-body">
                                                        <div class="row">
                                                            <div class="col-xs-4">
                                                                <img src="@modelBrand.ImagePath" />
                                                            </div>
                                                            <div class="col-xs-8">
                                                                @modelBrand.BrandName
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>}
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <!-- /.content -->
            </div>
            <!-- /.container -->
        </div>
        <!-- /.content-wrapper -->
        @{
            Html.RenderPartial("Footer", null);
        }
    </div>
    <!-- ./wrapper -->
    <!-- jQuery 3 -->
    <script src="~/Assets/bower_components/jquery/dist/jquery.min.js"></script>
<script src="~/Assets/bower_components/slick/slick.min.js"></script>
    <script src="~/Scripts/jquery.signalR-2.2.3.min.js"></script>
    <script src="~/signalr/js"></script>

    <!-- Bootstrap 3.3.7 -->
    <script src="~/Assets/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- SlimScroll -->
    <script src="~/Assets/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="~/Assets/bower_components/fastclick/lib/fastclick.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Assets/bower_components/toastr/toastr.js"></script>
    <script src="~/Assets/Assets/js/util.js"></script>

    <script src="~/Assets/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/Assets/Assets/js/util.js"></script>
    <script src="~/Assets/Assets/js/signalRLib.js"></script>
    <script>
    $(function() {
        @if (SessionService.UserId != "")
        {
            @:startSignalR('@SessionService.GetClientId()');
        }
    });

    </script>

</body>
</html>

FYPWeb/Views/Home/AllCompanies.cshtml
@using FYPWeb.Service
@using FYPWeb.ViewModels
@model AllCompanyViewModal
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>OMDM | All Diseases</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="~/Assets/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Assets/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="~/Assets/bower_components/Ionicons/css/ionicons.min.css">
    <link rel="stylesheet" href="~/Assets/bower_components/slick/slick.css">
    <link rel="stylesheet" href="~/Assets/bower_components/slick/slick-theme.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Assets/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="~/Assets/dist/css/skins/_all-skins.min.css">
    <link rel="stylesheet" href="~/Assets/bower_components/toastr/toastr.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<!-- ADD THE CLASS layout-top-nav TO REMOVE THE SIDEBAR. -->
<body class="hold-transition skin-green layout-top-nav">
    <div class="wrapper">
        @{
            Html.RenderPartial("Header", Model.HeaderViewModel);
        }
        <!-- Full Width Column -->
        <div class="content-wrapper">
            <div class="container">
                <section class="content">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="box box-solid box-success">
                                <div class="box-header">
                                    All Companies
                                </div>
                                <div class="box-body">
                                    <div class="row">
                                        <div class="col-xs-12">
                                            <ul class="pagination" id="brandPagination">
                                                @if (Model.Page > 1)
                                                {
                                                    <li>
                                                        <a href="@Url.Action("AllCompanies", "Home", new {parameter = Model.Parameter, page = 1})"><< First</a>
                                                    </li>
                                                    <li>
                                                        <a href="@Url.Action("AllCompanies", "Home", new {parameter = Model.Parameter, page = Model.Page - 1})">< Prev</a>
                                                    </li>
                                                }
                                                <li class="active">
                                                    <a href="@Url.Action("AllCompanies", "Home", new {parameter = Model.Parameter, page = Model.Page})">@Model.Page</a>
                                                </li>
                                                @if (Model.Page + 1 <= Model.PageCount)
                                                {
                                                    <li class="">
                                                        <a href="@Url.Action("AllCompanies", "Home", new {parameter = Model.Parameter, page = Model.Page + 1})">@(Model.Page + 1)</a>
                                                    </li>
                                                }
                                                @if (Model.Page + 2 <= Model.PageCount)
                                                {
                                                    <li class="">
                                                        <a href="@Url.Action("AllCompanies", "Home", new {parameter = Model.Parameter, page = Model.Page + 2})">@(Model.Page + 2)</a>
                                                    </li>
                                                }
                                                @if (Model.Page < Model.PageCount)
                                                {
                                                    <li>
                                                        <a href="@Url.Action("AllCompanies", "Home", new {parameter = Model.Parameter, page = Model.Page + 1})">Next ></a>
                                                    </li>
                                                    <li>
                                                        <a href="@Url.Action("AllCompanies", "Home", new {parameter = Model.Parameter, page = Model.PageCount})">Last >></a>
                                                    </li>
                                                }
                                            </ul>

                                        </div>
                                    </div>
                                    @foreach (var modelCompany in Model.Companies)
                                    {
                                        <div class="row" style="cursor: pointer" onclick="goToUrl('@Url.Action("Index","Company",new {id = modelCompany.Id})')">
                                            <div class="col-xs-12">
                                                <div class="panel panel-default">
                                                    <div class="panel-body">
                                                        <div class="row">
                                                            <div class="col-xs-1">
                                                                <img class="img-responsive" src="@modelCompany.ImagePath" height="128" alt="" />
                                                            </div>
                                                            <div class="col-xs-9">
                                                                <div class="row">
                                                                    <div class="col-xs-12 text-bold">
                                                                        @modelCompany.CompanyName
                                                                    </div>
                                                                </div>
                                                                <div class="row">
                                                                    <div class="col-xs-12">
                                                                        @modelCompany.Address
                                                                    </div>
                                                                </div>
                                                            </div>

                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <!-- /.content -->
            </div>
            <!-- /.container -->
        </div>
        <!-- /.content-wrapper -->
        @{
            Html.RenderPartial("Footer", null);
        }
    </div>
    <!-- ./wrapper -->
    <!-- jQuery 3 -->
    <script src="~/Assets/bower_components/jquery/dist/jquery.min.js"></script>
<script src="~/Assets/bower_components/slick/slick.min.js"></script>
    <script src="~/Scripts/jquery.signalR-2.2.3.min.js"></script>
    <script src="~/signalr/js"></script>

    <!-- Bootstrap 3.3.7 -->
    <script src="~/Assets/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- SlimScroll -->
    <script src="~/Assets/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="~/Assets/bower_components/fastclick/lib/fastclick.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Assets/bower_components/toastr/toastr.js"></script>
    <script src="~/Assets/Assets/js/util.js"></script>

    <script src="~/Assets/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
<script src="~/Assets/Assets/js/util.js"></script>
    <script src="~/Assets/Assets/js/signalRLib.js"></script>

    <script>
    $(function() {
        @if (SessionService.UserId != "")
        {
            @:startSignalR('@SessionService.GetClientId()');
        }
    });

    </script>

</body>
</html>

FYPWeb/Views/Home/SendEmail.cshtml
@model FYPWeb.ViewModels.SendEmailViewModel
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>OMDM | Email Sent</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="~/Assets/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Assets/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="~/Assets/bower_components/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Assets/dist/css/AdminLTE.min.css">
    <!-- iCheck -->
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
    <div class="login-box">
        <div class="login-logo center-block">
            <a href="@(Url.Action("Index","Home"))" style="margin: 10px">
                <img src="~/Assets/Assets/img/OMDM-logo-horizontal-small.png" class="img-responsive center-block">
            </a>
        </div>
        <!-- /.login-logo -->
        <div class="login-box-body">
            <p class="login-box-msg">Email has been Sent to</p>
            <p class="text-center Bold text-green">
                @Model.Email
            </p>
        </div>
        <!-- /.login-box-body -->
    </div>
    <!-- /.login-box -->
    <!-- jQuery 3 -->
    <script src="~/Assets/bower_components/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="~/Assets/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<script>
    setTimeout(function () { window.location = "/Home/Index"; }, 5000);
</script>
</body>
</html>