FYPWeb/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FYPWeb.Repository.Repository;
using FYPWeb.Service;
using FYPWeb.ViewModels;
using Model.Entity;

namespace FYPWeb.Controllers
{
    public class CartController : Controller
    {
        private readonly DrugCartRepository _drugCartRepository;
        private readonly PharmacyRepository _pharmacyRepository;
        private readonly SessionCartRepository _sessionCartRepository;
        private readonly InventoryTrackRepository _inventoryTrackRepository;
        public CartController(DrugCartRepository drugCartRepository, PharmacyRepository pharmacyRepository, SessionCartRepository sessionCartRepository, PharmacyRepository pharmacyRepository1, InventoryTrackRepository inventoryTrackRepository)
        {
            _drugCartRepository = drugCartRepository;
            _sessionCartRepository = sessionCartRepository;
            _pharmacyRepository = pharmacyRepository1;
            _inventoryTrackRepository = inventoryTrackRepository;
        }

        public ActionResult Index()
        {
            if (SessionService.UserId == "Pharmacist")
                return RedirectToAction("Index", "Home");

            if (SessionService.UserId != "")
            {
                var id = int.Parse(SessionService.UserId);

                var d = new HomeCartViewModel()
                {
                    HeaderViewModel = new HomeHeaderViewModel()
                    {
                        Header = HomeHeader.None,
                        CartCount = _drugCartRepository.GetUniqueMedicineCountByUserId(id),
                        NotificationCount = 0,
                    },
                    DrugCarts = _drugCartRepository.GetByUserId(id),
                };
                if (d.DrugCarts.Any())
                {
                    var listOfSelected =
                        d.DrugCarts.GroupBy(p => p.Inventory.PharmacyId)
                            .Select(p => p.FirstOrDefault().Inventory.Pharmacy);
                    d.Pharmacies = listOfSelected;
                }
                return View("Index", d);
            }
            else
            {
                var d = new HomeCartViewModel()
                {
                    HeaderViewModel = new HomeHeaderViewModel()
                    {
                        Header = HomeHeader.None,
                        CartCount = _sessionCartRepository.GetUniqueMedicineCountBySessionId(SessionService.SessionId),
                        NotificationCount = 0,
                    },
                    DrugCarts = _sessionCartRepository.GetBySessionId(SessionService.SessionId).Select(p => new DrugCart()
                    {
                        InventoryId = p.InventoryId,
                        Inventory = p.Inventory,
                        Quantity = p.Quantity,
                    }),
                };
                if (d.DrugCarts.Any())
                {
                    var listOfSelected =
                        d.DrugCarts.GroupBy(p => p.Inventory.PharmacyId)
                            .Select(p => p.FirstOrDefault().Inventory.Pharmacy);
                    d.Pharmacies = listOfSelected;
                }
                return View("Index", d);

            }
        }
    }
}

FYPWeb/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FYPWeb.Repository.Repository;
using FYPWeb.Service;
using FYPWeb.ViewModels;

namespace FYPWeb.Controllers
{
    public class OrderController : Controller
    {
        private readonly PharmacyRepository _pharmacyRepository;
        private readonly DrugCartRepository _drugCartRepository;
        private readonly PrescriptionRepository _prescriptionRepository;
        private readonly PromotionRepository _promotionRepository;
        public OrderController(PharmacyRepository pharmacyRepository, DrugCartRepository drugCartRepository, PrescriptionRepository prescriptionRepository, PromotionRepository promotionRepository)
        {
            _pharmacyRepository = pharmacyRepository;
            _drugCartRepository = drugCartRepository;
            _prescriptionRepository = prescriptionRepository;
            _promotionRepository = promotionRepository;
        }


        public ActionResult PlaceOrder()
        {
            int i = 0;
            if (SessionService.UserId != "" && SessionService.UserRole == "Customer")
            {
                    i = _drugCartRepository.GetUniqueMedicineCountByUserId(int.Parse(SessionService.UserId));
                    var model = new PlaceOrderViewModel()
                    {
                        HeaderViewModel = new HomeHeaderViewModel()
                        {
                            Header = HomeHeader.None,
                            CartCount = i,
                            NotificationCount = 0,
                        },
                        DrugCarts = _drugCartRepository.GetByUserId(int.Parse(SessionService.UserId)),
                        Prescriptions = _prescriptionRepository.GetByUserId(int.Parse(SessionService.UserId)),
                    };
                    return View("PlaceOrder", model);
            }
            return RedirectToAction("Index", "Home");
        }

        public ActionResult PlaceOrderPrescription()
        {
            int i = 0;
            if (SessionService.UserId != "" && SessionService.UserRole == "Customer")
            {
                i = _drugCartRepository.GetUniqueMedicineCountByUserId(int.Parse(SessionService.UserId));
                var model = new PlaceOrderPrescriptionViewModel()
                {
                    HeaderViewModel = new HomeHeaderViewModel()
                    {
                        Header = HomeHeader.None,
                        CartCount = i,
                        NotificationCount = 0,
                    },
                    Prescriptions = _prescriptionRepository.GetByUserId(int.Parse(SessionService.UserId)),
                    Pharmacies = _pharmacyRepository.GetAllApprovedPharmacies(1,50)
                };
                return View("PlaceOrderPrescription", model);
            }
            return RedirectToAction("Index", "Home");
        }
    }

}

FYPWeb/Controllers/ProfileController.cs
using System;
using System.Diagnostics;
using System.Linq;
using System.Web.Mvc;
using FYPWeb.Repository.Repository;
using FYPWeb.Service;
using FYPWeb.ViewModels;

namespace FYPWeb.Controllers
{
    public class ProfileController : Controller
    {
        private readonly UserRepository _userRepository;
        private readonly PharmacyRepository _pharmacyRepository;
        private readonly DrugCartRepository _drugCartRepository;
        private readonly PharmacistReviewRepository _pharmacistReviewRepository;
        private readonly InventoryTrackRepository _inventoryRepository;
        public ProfileController(UserRepository userRepository, PharmacyRepository pharmacyRepository, DrugCartRepository drugCartRepository, PharmacistReviewRepository pharmacistReviewRepository, InventoryTrackRepository inventoryRepository)
        {
            _userRepository = userRepository;
            _pharmacyRepository = pharmacyRepository;
            _drugCartRepository = drugCartRepository;
            _pharmacistReviewRepository = pharmacistReviewRepository;
            _inventoryRepository = inventoryRepository;
        }

        public ActionResult Index(string username,int page = 1)
        {
            try
            {
                int c = 0;
                if (SessionService.UserId != "")
                {
                    c = _drugCartRepository.GetUniqueMedicineCountByUserId(int.Parse(SessionService.UserId));
                }
                var user = _userRepository.GetByUsername(username);
                if (user != null)
                {
                    if (user.UserRoleId == 2)
                    {
                        var m = new HomeProfileViewModel()
                        {
                            User = user,
                            HeaderViewModel = new HomeHeaderViewModel()
                            {
                                Header = HomeHeader.None,
                                CartCount = c,
                            },
                        };
                        return View("CustomerProfile", m);
                    }
                    else if(user.UserRoleId == 3)
                    {
                        var m = new HomeProfileViewModel()
                        {
                            User = user,
                            HeaderViewModel = new HomeHeaderViewModel()
                            {
                                Header = HomeHeader.None,
                                CartCount = c,
                            },
                            Pharmacy = _pharmacyRepository.GetApprovedPharmaciesByUserId(user.Id).FirstOrDefault(),
                        };
                        if (m.Pharmacy != null)
                        {
                            m.InventoryTracks = _inventoryRepository.GetDrugsByPharmacyId(m.Pharmacy.Id,page,12);
                            m.Page = page;
                            m.PageCount = _inventoryRepository.GetDrugsByPharmacyIdCount(m.Pharmacy.Id, 12);
                        }
                        return View("PharmacistProfile", m);
                    }
                }
            }
            catch (Exception e)
            {
                Debug.WriteLine(e);
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

FYPWeb/Views/Cart/Index.cshtml
@using FYPWeb.Service
@model FYPWeb.ViewModels.HomeCartViewModel
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@SessionService.FullName | My Cart</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="~/Assets/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Assets/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="~/Assets/bower_components/Ionicons/css/ionicons.min.css">
    <link rel="stylesheet" href="~/Assets/bower_components/slick/slick.css">
    <link rel="stylesheet" href="~/Assets/bower_components/slick/slick-theme.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Assets/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="~/Assets/dist/css/skins/_all-skins.min.css">
    <link rel="stylesheet" href="~/Assets/bower_components/toastr/toastr.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<!-- ADD THE CLASS layout-top-nav TO REMOVE THE SIDEBAR. -->
<body class="hold-transition skin-green layout-top-nav">
    <div class="wrapper">
        @{
            Html.RenderPartial("~/Views/Home/Header.cshtml", Model.HeaderViewModel);
        }
        <!-- Full Width Column -->
        <div class="content-wrapper">
            <div class="container">
                <section class="content">
                    <div class="box box-solid box-success">
                        <div class="box-header">
                            My Cart
                        </div>
                        <div class="box-body">
                            <table class="table table-responsive table-bordered">
                                @if (Model.DrugCarts.Any())
                                {

                                    <thead>
                                        <tr>
                                            <th>
                                                Pharmacy
                                            </th>
                                            <th>
                                                Medicine Name
                                            </th>
                                            <th>
                                                Qty
                                            </th>
                                            <th>
                                                Price
                                            </th>
                                            <th>
                                                Total
                                            </th>
                                            <th>
                                                Option
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var c in Model.DrugCarts)
                                        {
                                            <tr>
                                                <td>
                                                    @(c.Inventory.Pharmacy.ShopName)
                                                </td>
                                                <td>
                                                    @(c.Inventory.Drug.Brand + " - " + c.Inventory.Drug.DrugName)
                                                </td>
                                                <td>
                                                    X @c.Quantity
                                                </td>
                                                <td>
                                                    Rs @c.Inventory.Price
                                                </td>
                                                <td>
                                                    Rs @(c.Inventory.Price * c.Quantity)
                                                </td>
                                                <td>
                                                    <button class="btn btn-info" onclick="showeditDialogCart(@c.InventoryId, @c.UserId, '@SessionService.SessionId')">Update</button>
                                                    <button class="btn btn-danger" onclick="showdeleteDialogCart(@c.InventoryId, @c.UserId, '@SessionService.SessionId')">Remove</button>
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <th>

                                            </th>
                                            <th>

                                            </th>
                                            <th>

                                            </th>
                                            <th>
                                                Total
                                            </th>
                                            <th>
                                                Rs @Model.DrugCarts.Sum(p => p.Quantity * p.Inventory.Price)
                                            </th>
                                        </tr>
                                    </tfoot>
                                }
                                else
                                {
                                    <tr>
                                        <td colspan="6" style="text-align: center">No Items in Cart</td>
                                    </tr>
                                }
                            </table>
                            @if (SessionService.UserId == "")
                            {
                                <button class="btn btn-success" onclick="showLoginRegsiterForm()">Place Order</button>
                            }
                            else
                            {
                                <a class="btn btn-success" href="@Url.Action("PlaceOrder","Order")">Place Order</a>
                            }
                        </div>
                    </div>
                    <div class="box box-success box-solid">
                        <div class="box-header">
                            Pharmacies Containing these Medicines
                        </div>
                        <div class="box-body chat">
                            @if (Model.Pharmacies != null)
                            {
                                foreach (var p in Model.Pharmacies)
                                {
                                    <div class="item">
                                        <img src="@p.ImagePath" alt="user image" class="online">

                                        <p class="message">
                                            <a href="@Url.Action("Index", "Profile", new {username = p.User.Username})" class="name">
                                                @(p.ShopName)
                                            </a>
                                            <i class="fa fa-star" style="color: gold"></i> @(p.PharmacyReviews.Any() ? p.PharmacyReviews.Average(pr => pr.Rating).ToString("0.00") : "0") / 5
                                            <br/>
                                            @p.ShopAddress
                                        </p>
                                        <!-- /.attachment -->
                                    </div>
                                }
                            }
                            else
                            {
                                
                            }
                        </div>
                    </div>
                
                </section>
                <!-- /.content -->
            </div>
            <!-- /.container -->
        </div>
        <!-- /.content-wrapper -->
        @{
            Html.RenderPartial("~/Views/Home/Footer.cshtml", null);
        }
    </div>
    <!-- ./wrapper -->
    <!-- jQuery 3 -->
    <script src="~/Assets/bower_components/jquery/dist/jquery.min.js"></script>
    <script src="~/Assets/bower_components/slick/slick.min.js"></script>
    <script src="~/Scripts/jquery.signalR-2.2.3.min.js"></script>
    <script src="~/signalr/js"></script>

    <!-- Bootstrap 3.3.7 -->
    <script src="~/Assets/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- SlimScroll -->
    <script src="~/Assets/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="~/Assets/bower_components/fastclick/lib/fastclick.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Assets/bower_components/toastr/toastr.js"></script>

    <script src="~/Assets/Assets/js/util.js"></script>
    <script src="~/Assets/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/Assets/Assets/js/cart.js"></script>
    <script src="~/Assets/Assets/js/signalRLib.js"></script>
    <script>
    @if (SessionService.UserId != "")
    {
        @:startSignalR('@SessionService.GetClientId()');
    }
    </script>
    <script>
    $(function () {
        $(".slimScrollDiv").slimScroll({
            height: '250px'
        });
        @if (SessionService.UserId != "")
        {
            @:startSignalR('@SessionService.GetClientId()');
        }
    });
    </script>

</body>
</html>